[package]
authors.workspace      = true
categories.workspace   = true
description            = "Serialization/deserialization utilities for Miden"
documentation          = "https://docs.rs/miden-serde-utils"
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
name                   = "miden-serde-utils"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[features]
default       = ["std"]
p3-compat     = ["dep:p3-field", "dep:p3-goldilocks"]
std           = ["winter-math?/std", "winter-utils?/std"]
winter-compat = ["dep:winter-math", "dep:winter-utils"]

[dependencies]
p3-field      = { branch = "main", default-features = false, git = "https://github.com/Plonky3/Plonky3", optional = true }
p3-goldilocks = { branch = "main", default-features = false, git = "https://github.com/Plonky3/Plonky3", optional = true }
winter-math   = { default-features = false, optional = true, version = "0.13" }
winter-utils  = { default-features = false, optional = true, version = "0.13" }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["winter-math", "winter-utils"]
