[package]
authors.workspace      = true
categories.workspace   = true
description            = "Serialization/deserialization utilities for Miden"
documentation          = "https://docs.rs/miden-serde-utils"
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
name                   = "miden-serde-utils"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[features]
default       = ["std"]
std           = ["winter-air?/std", "winter-crypto?/std", "winter-math?/std", "winter-utils?/std"]
winter-compat = ["dep:winter-air", "dep:winter-crypto", "dep:winter-math", "dep:winter-utils"]

[dependencies]
winter-air    = { default-features = false, optional = true, version = "0.13" }
winter-crypto = { default-features = false, optional = true, version = "0.13" }
winter-math   = { default-features = false, optional = true, version = "0.13" }
winter-utils  = { default-features = false, optional = true, version = "0.13" }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["winter-air", "winter-crypto", "winter-math", "winter-utils"]
